version: '3.6'
services:
  postgis:
    image: postgis/postgis
    ports:
      - 5432:5432
    environment:
      - &postgis-db POSTGRES_DB=postgis
      - &postgis-url POSTGRES_URL=postgis
      - &postgis-user POSTGRES_USER=postgres
      - &postgis-pass POSTGRES_PASSWORD=postgres
    volumes:
      - /data/urban-sdk/postgresql:/var/lib/postgresql

  flask:
    build:
      context: .
    image: urban-sdk-flask
    volumes:
      - ./:/app
    ports:
      - 5000:5000
    links:
      - postgis
    environment:
      - *postgis-db
      - *postgis-url
      - *postgis-user
      - *postgis-pass
      - FLASK_APP=app.py
      - FLASK_ENV=DEVELOPMENT
      - FLASK_DEBUG=1
